import unittest
from unittest.mock import patch, MagicMock
from brasilapy import BrasilAPI
from brasilapy.constants import IBGEProvider

class TestBrasilAPI(unittest.TestCase):

    @patch('brasilapy.BrasilAPI.get_ibge_municipios')
    def test_get_ibge_municipios(self, mock_get_ibge_municipios):
        # Define a resposta mock
        municipios_mock = [
            MagicMock(nome="AGUA BRANCA", codigo_ibge="2500106"),
            MagicMock(nome="AGUIAR", codigo_ibge="2500205"),
            MagicMock(nome="ALAGOA GRANDE", codigo_ibge="2500304"),
            MagicMock(nome="ALAGOA NOVA", codigo_ibge="2500403"),
            MagicMock(nome="ALAGOINHA", codigo_ibge="2500502"),
            MagicMock(nome="ALCANTIL", codigo_ibge="2500536"),
            MagicMock(nome="ALGODAO DE JANDAIRA", codigo_ibge="2500577"),
            MagicMock(nome="ALHANDRA", codigo_ibge="2500601"),
            MagicMock(nome="SAO JOAO DO RIO DO PEIXE", codigo_ibge="2500700"),
            MagicMock(nome="AMPARO", codigo_ibge="2500734"),
            MagicMock(nome="APARECIDA", codigo_ibge="2500775"),
            MagicMock(nome="ARACAGI", codigo_ibge="2500809"),
            MagicMock(nome="ARARA", codigo_ibge="2500908"),
            MagicMock(nome="ARARUNA", codigo_ibge="2501005"),
            MagicMock(nome="AREIA", codigo_ibge="2501104"),
            MagicMock(nome="AREIA DE BARAUNAS", codigo_ibge="2501153"),
            MagicMock(nome="AREIAL", codigo_ibge="2501203"),
            MagicMock(nome="AROEIRAS", codigo_ibge="2501302"),
            MagicMock(nome="ASSUNCAO", codigo_ibge="2501351"),
            MagicMock(nome="BAIA DA TRAICAO", codigo_ibge="2501401"),
            MagicMock(nome="BANANEIRAS", codigo_ibge="2501500"),
            MagicMock(nome="BARAUNA", codigo_ibge="2501534"),
            MagicMock(nome="BARRA DE SANTANA", codigo_ibge="2501575"),
            MagicMock(nome="BARRA DE SANTA ROSA", codigo_ibge="2501609"),
            MagicMock(nome="BARRA DE SAO MIGUEL", codigo_ibge="2501708"),
            MagicMock(nome="BAYEUX", codigo_ibge="2501807"),
            MagicMock(nome="BELEM", codigo_ibge="2501906"),
            MagicMock(nome="BELEM DO BREJO DO CRUZ", codigo_ibge="2502003"),
            MagicMock(nome="BERNARDINO BATISTA", codigo_ibge="2502052"),
            MagicMock(nome="BOA VENTURA", codigo_ibge="2502102"),
            MagicMock(nome="BOA VISTA", codigo_ibge="2502151"),
            MagicMock(nome="BOM JESUS", codigo_ibge="2502201"),
            MagicMock(nome="BOM SUCESSO", codigo_ibge="2502300"),
            MagicMock(nome="BONITO DE SANTA FE", codigo_ibge="2502409"),
            MagicMock(nome="BOQUEIRAO", codigo_ibge="2502508"),
            MagicMock(nome="IGARACY", codigo_ibge="2502607"),
            MagicMock(nome="BORBOREMA", codigo_ibge="2502706"),
            MagicMock(nome="BREJO DO CRUZ", codigo_ibge="2502805"),
            MagicMock(nome="BREJO DOS SANTOS", codigo_ibge="2502904"),
            MagicMock(nome="CAAPORA", codigo_ibge="2503001"),
            MagicMock(nome="CABACEIRAS", codigo_ibge="2503100"),
            MagicMock(nome="CABEDELO", codigo_ibge="2503209"),
            MagicMock(nome="CACHOEIRA DOS INDIOS", codigo_ibge="2503308"),
            MagicMock(nome="CACIMBA DE AREIA", codigo_ibge="2503407"),
            MagicMock(nome="CACIMBA DE DENTRO", codigo_ibge="2503506"),
            MagicMock(nome="CACIMBAS", codigo_ibge="2503555"),
            MagicMock(nome="CAICARA", codigo_ibge="2503605"),
            MagicMock(nome="CAJAZEIRAS", codigo_ibge="2503704"),
            MagicMock(nome="CAJAZEIRINHAS", codigo_ibge="2503753"),
            MagicMock(nome="CALDAS BRANDAO", codigo_ibge="2503803"),
            MagicMock(nome="CAMALAU", codigo_ibge="2503902"),
            MagicMock(nome="CAMPINA GRANDE", codigo_ibge="2504009"),
            MagicMock(nome="CAPIM", codigo_ibge="2504033"),
            MagicMock(nome="CARAUBAS", codigo_ibge="2504074"),
            MagicMock(nome="CARRAPATEIRA", codigo_ibge="2504108"),
            MagicMock(nome="CASSERENGUE", codigo_ibge="2504157"),
            MagicMock(nome="CATINGUEIRA", codigo_ibge="2504207"),
            MagicMock(nome="CATOLE DO ROCHA", codigo_ibge="2504306"),
            MagicMock(nome="CATURITE", codigo_ibge="2504355"),
            MagicMock(nome="CONCEICAO", codigo_ibge="2504405"),
            MagicMock(nome="CONDADO", codigo_ibge="2504504"),
            MagicMock(nome="CONDE", codigo_ibge="2504603"),
            MagicMock(nome="CONGO", codigo_ibge="2504702"),
            MagicMock(nome="COREMAS", codigo_ibge="2504801"),
            MagicMock(nome="COXIXOLA", codigo_ibge="2504850"),
            MagicMock(nome="CRUZ DO ESPIRITO SANTO", codigo_ibge="2504900"),
            MagicMock(nome="CUBATI", codigo_ibge="2505006"),
            MagicMock(nome="CUITE", codigo_ibge="2505105"),
            MagicMock(nome="CUITEGI", codigo_ibge="2505204"),
            MagicMock(nome="CUITE DE MAMANGUAPE", codigo_ibge="2505238"),
            MagicMock(nome="CURRAL DE CIMA", codigo_ibge="2505279"),
            MagicMock(nome="CURRAL VELHO", codigo_ibge="2505303"),
            MagicMock(nome="DAMIAO", codigo_ibge="2505352"),
            MagicMock(nome="DESTERRO", codigo_ibge="2505402"),
            MagicMock(nome="VISTA SERRANA", codigo_ibge="2505501"),
            MagicMock(nome="DIAMANTE", codigo_ibge="2505600"),
            MagicMock(nome="DONA INES", codigo_ibge="2505709"),
            MagicMock(nome="DUAS ESTRADAS", codigo_ibge="2505808"),
            MagicMock(nome="EMAS", codigo_ibge="2505907"),
            MagicMock(nome="ESPERANCA", codigo_ibge="2506004"),
            MagicMock(nome="FAGUNDES", codigo_ibge="2506103"),
            MagicMock(nome="FREI MARTINHO", codigo_ibge="2506202"),
            MagicMock(nome="GADO BRAVO", codigo_ibge="2506251"),
            MagicMock(nome="GUARABIRA", codigo_ibge="2506301"),
            MagicMock(nome="GURINHEM", codigo_ibge="2506400"),
            MagicMock(nome="GURJAO", codigo_ibge="2506509"),
            MagicMock(nome="IBIARA", codigo_ibge="2506608"),
            MagicMock(nome="IMACULADA", codigo_ibge="2506707"),
            MagicMock(nome="INGA", codigo_ibge="2506806"),
            MagicMock(nome="ITABAIANA", codigo_ibge="2506905"),
            MagicMock(nome="ITAPORANGA", codigo_ibge="2507002"),
            MagicMock(nome="ITAPOROROCA", codigo_ibge="2507101"),
            MagicMock(nome="ITATUBA", codigo_ibge="2507200"),
            MagicMock(nome="JACARAU", codigo_ibge="2507309"),
            MagicMock(nome="JERICO", codigo_ibge="2507408"),
            MagicMock(nome="JOAO PESSOA", codigo_ibge="2507507"),
            MagicMock(nome="JUAREZ TAVORA", codigo_ibge="2507606"),
            MagicMock(nome="JUAZEIRINHO", codigo_ibge="2507705"),
            MagicMock(nome="JUNCO DO SERIDO", codigo_ibge="2507804"),
            MagicMock(nome="JURIPIRANGA", codigo_ibge="2507903"),
            MagicMock(nome="JURU", codigo_ibge="2508000"),
            MagicMock(nome="LAGOA", codigo_ibge="2508109"),
            MagicMock(nome="LAGOA DE DENTRO", codigo_ibge="2508208"),
            MagicMock(nome="LAGOA SECA", codigo_ibge="2508307"),
            MagicMock(nome="LASTRO", codigo_ibge="2508406"),
            MagicMock(nome="LIVRAMENTO", codigo_ibge="2508505"),
            MagicMock(nome="LOGRADOURO", codigo_ibge="2508554"),
            MagicMock(nome="LUCENA", codigo_ibge="2508604"),
            MagicMock(nome="MAE D AGUA", codigo_ibge="2508703"),
            MagicMock(nome="MALTA", codigo_ibge="2508802"),
            MagicMock(nome="MAMANGUAPE", codigo_ibge="2508901"),
            MagicMock(nome="MANAIRA", codigo_ibge="2509008"),
            MagicMock(nome="MARCACAO", codigo_ibge="2509057"),
            MagicMock(nome="MARI", codigo_ibge="2509107"),
            MagicMock(nome="MARIZOPOLIS", codigo_ibge="2509156"),
            MagicMock(nome="MASSARANDUBA", codigo_ibge="2509206"),
            MagicMock(nome="MATARACA", codigo_ibge="2509305"),
            MagicMock(nome="MATINHAS", codigo_ibge="2509339"),
            MagicMock(nome="MATO GROSSO", codigo_ibge="2509370"),
            MagicMock(nome="MATUREIA", codigo_ibge="2509396"),
            MagicMock(nome="MOGEIRO", codigo_ibge="2509404"),
            MagicMock(nome="MONTADAS", codigo_ibge="2509503"),
            MagicMock(nome="MONTE HOREBE", codigo_ibge="2509602"),
            MagicMock(nome="MONTEIRO", codigo_ibge="2509701"),
            MagicMock(nome="MULUNGU", codigo_ibge="2509800"),
            MagicMock(nome="NATUBA", codigo_ibge="2509909"),
            MagicMock(nome="NAZAREZINHO", codigo_ibge="2510006"),
            MagicMock(nome="NOVA FLORESTA", codigo_ibge="2510105"),
            MagicMock(nome="NOVA OLINDA", codigo_ibge="2510204"),
            MagicMock(nome="NOVA PALMEIRA", codigo_ibge="2510303"),
            MagicMock(nome="OLHO D AGUA", codigo_ibge="2510402"),
            MagicMock(nome="OLIVEDOS", codigo_ibge="2510501"),
            MagicMock(nome="OURO VELHO", codigo_ibge="2510600"),
            MagicMock(nome="PARARI", codigo_ibge="2510659"),
            MagicMock(nome="PASSAGEM", codigo_ibge="2510709"),
            MagicMock(nome="PATOS", codigo_ibge="2510808"),
            MagicMock(nome="PAULISTA", codigo_ibge="2510907"),
            MagicMock(nome="PEDRA BRANCA", codigo_ibge="2511004"),
            MagicMock(nome="PEDRA LAVRADA", codigo_ibge="2511103"),
            MagicMock(nome="PEDRAS DE FOGO", codigo_ibge="2511202"),
            MagicMock(nome="PIANCO", codigo_ibge="2511301"),
            MagicMock(nome="PICUI", codigo_ibge="2511400"),
            MagicMock(nome="PILAR", codigo_ibge="2511509"),
            MagicMock(nome="PILOES", codigo_ibge="2511608"),
            MagicMock(nome="PILOEZINHOS", codigo_ibge="2511707"),
            MagicMock(nome="PIRPIRITUBA", codigo_ibge="2511806"),
            MagicMock(nome="PITIMBU", codigo_ibge="2511905"),
            MagicMock(nome="POCINHOS", codigo_ibge="2512002"),
            MagicMock(nome="POCO DANTAS", codigo_ibge="2512036"),
            MagicMock(nome="POCO DE JOSE DE MOURA", codigo_ibge="2512077"),
            MagicMock(nome="POMBAL", codigo_ibge="2512101"),
            MagicMock(nome="PRATA", codigo_ibge="2512200"),
            MagicMock(nome="PRINCESA ISABEL", codigo_ibge="2512309"),
            MagicMock(nome="PUXINANA", codigo_ibge="2512408"),
            MagicMock(nome="QUEIMADAS", codigo_ibge="2512507"),
            MagicMock(nome="QUIXABA", codigo_ibge="2512606"),
            MagicMock(nome="REMIGIO", codigo_ibge="2512705"),
            MagicMock(nome="PEDRO REGIS", codigo_ibge="2512721"),
            MagicMock(nome="RIACHAO", codigo_ibge="2512747"),
            MagicMock(nome="RIACHAO DO BACAMARTE", codigo_ibge="2512754"),
            MagicMock(nome="RIACHAO DO POCO", codigo_ibge="2512762"),
            MagicMock(nome="RIACHO DE SANTO ANTONIO", codigo_ibge="2512788"),
            MagicMock(nome="RIACHO DOS CAVALOS", codigo_ibge="2512804"),
            MagicMock(nome="RIO TINTO", codigo_ibge="2512903"),
            MagicMock(nome="SALGADINHO", codigo_ibge="2513000"),
            MagicMock(nome="SALGADO DE SAO FELIX", codigo_ibge="2513109"),
            MagicMock(nome="SANTA CECILIA", codigo_ibge="2513158"),
            MagicMock(nome="SANTA CRUZ", codigo_ibge="2513208"),
            MagicMock(nome="SANTA HELENA", codigo_ibge="2513307"),
            MagicMock(nome="SANTA INES", codigo_ibge="2513356"),
            MagicMock(nome="SANTA LUZIA", codigo_ibge="2513406"),
            MagicMock(nome="SANTANA DE MANGUEIRA", codigo_ibge="2513505"),
            MagicMock(nome="SANTANA DOS GARROTES", codigo_ibge="2513604"),
            MagicMock(nome="JOCA CLAUDINO", codigo_ibge="2513653"),
            MagicMock(nome="SANTA RITA", codigo_ibge="2513703"),
            MagicMock(nome="SANTA TERESINHA", codigo_ibge="2513802"),
            MagicMock(nome="SANTO ANDRE", codigo_ibge="2513851"),
            MagicMock(nome="SAO BENTO", codigo_ibge="2513901"),
            MagicMock(nome="SAO BENTINHO", codigo_ibge="2513927"),
            MagicMock(nome="SAO DOMINGOS DO CARIRI", codigo_ibge="2513943"),
            MagicMock(nome="SAO DOMINGOS", codigo_ibge="2513968"),
            MagicMock(nome="SAO FRANCISCO", codigo_ibge="2513984"),
            MagicMock(nome="SAO JOAO DO CARIRI", codigo_ibge="2514008"),
            MagicMock(nome="SAO JOAO DO TIGRE", codigo_ibge="2514107"),
            MagicMock(nome="SAO JOSE DA LAGOA TAPADA", codigo_ibge="2514206"),
            MagicMock(nome="SAO JOSE DE CAIANA", codigo_ibge="2514305"),
            MagicMock(nome="SAO JOSE DE ESPINHARAS", codigo_ibge="2514404"),
            MagicMock(nome="SAO JOSE DOS RAMOS", codigo_ibge="2514453"),
            MagicMock(nome="SAO JOSE DE PIRANHAS", codigo_ibge="2514503"),
            MagicMock(nome="SAO JOSE DE PRINCESA", codigo_ibge="2514552"),
            MagicMock(nome="SAO JOSE DO BONFIM", codigo_ibge="2514602"),
            MagicMock(nome="SAO JOSE DO BREJO DO CRUZ", codigo_ibge="2514651"),
            MagicMock(nome="SAO JOSE DO SABUGI", codigo_ibge="2514701"),
            MagicMock(nome="SAO JOSE DOS CORDEIROS", codigo_ibge="2514800"),
            MagicMock(nome="SAO MAMEDE", codigo_ibge="2514909"),
            MagicMock(nome="SAO MIGUEL DE TAIPU", codigo_ibge="2515005"),
            MagicMock(nome="SAO SEBASTIAO DE LAGOA DE ROCA", codigo_ibge="2515104"),
            MagicMock(nome="SAO SEBASTIAO DO UMBUZEIRO", codigo_ibge="2515203"),
            MagicMock(nome="SAPE", codigo_ibge="2515302"),
            MagicMock(nome="SERIDO", codigo_ibge="2515401"),
            MagicMock(nome="SERRA BRANCA", codigo_ibge="2515500"),
            MagicMock(nome="SERRA DA RAIZ", codigo_ibge="2515609"),
            MagicMock(nome="SERRA GRANDE", codigo_ibge="2515708"),
            MagicMock(nome="SERRA REDONDA", codigo_ibge="2515807"),
            MagicMock(nome="SERRARIA", codigo_ibge="2515906"),
            MagicMock(nome="SERTAOZINHO", codigo_ibge="2515930"),
            MagicMock(nome="SOBRADO", codigo_ibge="2515971"),
            MagicMock(nome="SOLANEA", codigo_ibge="2516003"),
            MagicMock(nome="SOLEDADE", codigo_ibge="2516102"),
            MagicMock(nome="SOSSEGO", codigo_ibge="2516151"),
            MagicMock(nome="SOUSA", codigo_ibge="2516201"),
            MagicMock(nome="SUME", codigo_ibge="2516300"),
            MagicMock(nome="TACIMA", codigo_ibge="2516409"),
            MagicMock(nome="TAPEROA", codigo_ibge="2516508"),
            MagicMock(nome="TAVARES", codigo_ibge="2516607"),
            MagicMock(nome="TEIXEIRA", codigo_ibge="2516706"),
            MagicMock(nome="TENORIO", codigo_ibge="2516755"),
            MagicMock(nome="TRIUNFO", codigo_ibge="2516805"),
            MagicMock(nome="UIRAUNA", codigo_ibge="2516904"),
            MagicMock(nome="UMBUZEIRO", codigo_ibge="2517001"),
            MagicMock(nome="VARZEA", codigo_ibge="2517100"),
            MagicMock(nome="VIEIROPOLIS", codigo_ibge="2517209"),
            MagicMock(nome="ZABELE", codigo_ibge="2517407")
        ]

        mock_get_ibge_municipios.return_value = municipios_mock

        client = BrasilAPI()
        municipios = client.get_ibge_municipios(state_uf="pb", providers=(IBGEProvider.DADOS_ABERTOS_BR,))
        
        # Verifica se o método foi chamado com os parâmetros corretos
        mock_get_ibge_municipios.assert_called_with(state_uf="pb", providers=(IBGEProvider.DADOS_ABERTOS_BR,))
        
        # Verifica se a resposta está correta
        self.assertEqual(len(municipios), len(municipios_mock))
        for i, municipio in enumerate(municipios_mock):
            self.assertEqual(municipios[i].nome, municipio.nome)
            self.assertEqual(municipios[i].codigo_ibge, municipio.codigo_ibge)

if __name__ == '__main__':
    unittest.main()
